pipeline {
   agent any


   stages {
      stage('pull') {

         steps{
            script {
                timeout(60) {
                   echo 'Hello World 1'
                   git credentialsId: 'b32ea6f5-379c-43ed-ad25-7cc34d95a52f', url: 'https://github.com/coolerzhu/test.git'
                }
            }
         }

      }
      stage('Build') {
          steps {
             echo 'Hello World 2'
             sh label: '', script: 'mvn clean package'
          }
      }

     stage('run') {
         steps {
            echo 'Hello World 3'
         }
     }
   }


}