pipeline {
   agent any


   stages {
      stage('pull') {
         steps {
            echo 'Hello World 1'
            git credentialsId: 'githob02', url: 'https://github.com/coolerzhu/test.git'
         }
      }
      stage('Build') {
          steps {
             echo 'Hello World 2'
          }
      }

     stage('run') {
         steps {
            echo 'Hello World 3'
         }
     }
   }


}